apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: rag-api:0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "ragdb"
            - name: DB_USER
              value: "raguser"
            - name: DB_PASSWORD
              value: "ragpassword"

            - name: OLLAMA_BASE_URL
              value: "http://192.168.0.46:11434"
              # value: "http://192.168.0.10:11434"
            - name: OLLAMA_MODEL
              value: "llama3.2:3b"

            - name: DOC_ROOT
              value: "/data/raw_docs"
            - name: TOP_K
              value: "4"
            - name: EMBED_MODEL_NAME
              value: "sentence-transformers/all-MiniLM-L6-v2"
          
          # ✅ (2) volumeMounts는 컨테이너 내부에 추가
          volumeMounts:
            - name: rag-docs
              mountPath: /data/raw_docs
              readOnly: true

          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "2Gi"
              cpu: "1"

      # ✅ (3) volumes는 containers 바깥(template.spec 레벨)에 추가
      volumes:
        - name: rag-docs
          hostPath:
            path: /data/raw_docs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: genai
spec:
  selector:
    app: rag-api
  ports:
    - name: http          # ✅ ServiceMonitor 쓸 거면 name: http 추천
      port: 8000
      targetPort: 8000
  type: ClusterIP
